### ISSUE TITLE
Ruby 3 support

### ISSUE THREAD

**Issue by taw** [beeminder/beeminder-gem#31]
Could you release a new version of the gem?

The most recent one is from 2018, and it depends on json 1.x, and that doesn't work on Ruby 3.

I see the gemspec was already fixed to not have dependency on json 1.x, so if you release what you have, it would fix Ruby 3 support.

**Comment by dreeves** [comment]
Thanks so much! On it. 

Background: https://dev.to/taw/open-source-adventures-episode-37-fixing-beeminder-gem-to-work-with-ruby-3-d1c

**Comment by dreeves** [comment]
http://beeminder.com/changelog#4116
